### ISSUE TITLE
Support image format of Skyrim Special edition

### ISSUE THREAD

**Issue by LePresidente** [TanninOne/modorganizer-game_gamebryo#6]
See https://github.com/TanninOne/modorganizer/issues/1017

grabbed from modded skyrim se plugin.
format has changed 320 px(?) 8888BGRX (24bit + 8bit alpha) px format BGR (flipped)

**Comment by LePresidente** [comment]
Ref to issue for release : https://github.com/TanninOne/modorganizer/issues/1026

**Comment by TanninOne** [comment]
The format is 320x192 8888RGBA.

Unfortunately there are further changes in the savegame format and apparently a bug that will make it impossible to read the list of plugins from the save. :(

**Comment by ZachHaber** [comment]
How does this look? I do believe that I got the plugins list to work as well. I haven't tested it thoroughly, which might be useful as it is a little hacky.
![image](https://cloud.githubusercontent.com/assets/19843782/21160190/802c5f88-c149-11e6-9e26-1b0345867cee.png)

**Comment by LePresidente** [comment]
Looks good, Tannin still reviews everything that goes into modorganizer. so hacky might be fine. once you ready do a pull request.

**Comment by ZachHaber** [comment]
I started a pull request earlier, then I tried it with more mods, and that's when the weirdness started. I pulled this from the save file. There are many plugins that have this problem, and the issues that happened were because it isn't the correct length, so it would read past the next string length which ends up being a much bigger number.
I seriously want to know how the game is able to properly read the plugin list from this mess...
So, I'll pull my changes, which forgoes even attempting to read the plugins.
![image](https://cloud.githubusercontent.com/assets/19843782/21169957/7bd49364-c186-11e6-874d-ac1c673b48a8.png)

**Comment by ZachHaber** [comment]
Pull request is here: https://github.com/LePresidente/modorganizer-game_skyrimSE/pull/2. There was no need to change anything in the gamebryosavegame class.

**Comment by LePresidente** [comment]
Yea i noticed all that when reading the issues for wyre-bash, looks like they added lz4 compression and so on, Though should probably make a new issue for the plugin list and  lz4 support since this issue is fixed.

[wrye-bash issue 338](https://github.com/wrye-bash/wrye-bash/issues/338)
[wrye-bash issue 330](https://github.com/wrye-bash/wrye-bash/issues/330)

**Comment by ZachHaber** [comment]
Huh, That would explain the weirdness. I'll take a look at trying to decompress the relevant parts of the save file.

**Comment by ZachHaber** [comment]
Muahahahahhahah! Got it to compile and work! Going to try and figure out how to make it better/more reusable. Probably going to make changes to gamebryo instead of just skyrimSE. I'm thinking a boolean flag called use_lz4 to make it decompress it. Thoughts?
![image](https://cloud.githubusercontent.com/assets/19843782/21176877/51a8619c-c1ae-11e6-957c-eaffd317cee0.png)

**Comment by TanninOne** [comment]
There is actually a flag in the save game itself. There is a 2-byte field between screenshot dimensions and screenshot data.
According to the linked wrye-bash issues that field says if the save game is uncompressed (0), zlib compressed (1) or lz4 compressed (2).
Hugues92 doesn't state where he got that information but maybe it's from research into the ba2 format.
I'm currently working under the assumption that this info is correct.

**Comment by LePresidente** [comment]
So Ideally the decompression should happen in gamebyro with an int passed from the plugin. if nothing is sent from the plugin assume no decompression.

Modorganizer-Umbrella has been updated to download lz4 so you will just need to update cmakelists to find it in gamebyro.

If i'm talking rubbish please let me know!

**Comment by TanninOne** [comment]
No, the decompression format should be decided on the fly when parsing the save game.
We don't know how Bethesda decides which compression is used. I'd be willing to bet good money that it's always lz4 but technically they could do something silly like "if the file is less than 5mb, use lz4, otherwise use zlib" and the only reason we only saw lz4 in savegames so far is because no one has tested with a huge savegame yet.

Usually I would argue: If they specify the compression format inside the file then it must be dynamic. But Bethesda is a bit inconsistent in such matters, i.e. screenshots are, to my knowledge, always the same size within a game and yet they specify those dimensions inside the file. On the other hand the image format (rgb vs rgba) is hard coded into the engine and the file contains no hint.

**Comment by ZachHaber** [comment]
https://github.com/ZachHaber/modorganizer-game_gamebryo/blob/master/src/gamebryosavegame.cpp
That's where I currently am at (more or less) on the lz4 in savegames. I have it working fine for just in the skyrimSEsavegame.cpp, but going for the more robust/reusable in gamebryo. Problem is, I'm trying to figure out a couple of things: firstly, the save game format changes with every game. For instance, in FO4, there is the string that is ignored after the image but before the plugins. My current methodology wouldn't work for that. Secondly, doing it the way I have would make lz4 (and later (if need be) zlib) a dependency for all the game plugins. 
https://github.com/ZachHaber/modorganizer-game_skyrimSE/blob/standalonePluginReading/src/skyrimsesavegame.cpp
My current idea for a solution is to turn readPlugins into a function in the gamebryosavegame class instead of the filewrapper class, which would enable the individual plugins to override the function if different functionality from the norm is needed.
It would also be fine to just add lz4 (and possibly zlib) to the dependencies of all the other game plugins to enable it to compile with the new decompression code.
